// A TRF ("Test Report Form")-style PDF combining a student's most
// recent Reading, Listening, Writing and Speaking results into one
// downloadable report — one of the "next level" picks from the
// original scoping doc, picked by Jasur 2026-09-25.
//
// Reading/Listening only ever have a raw percentage in this app
// (mock_attempts.score/max_score) — there's no official IELTS band for
// either until IDP actually grades a real sitting, so this ESTIMATES a
// band from that percentage (see ieltsBands.js) and labels it clearly
// as an estimate, never as a real score. Writing and Speaking bands are
// real, human-given bands from writing_mock_attempts.examiner_band /
// mock_speaking_slots.examiner_band — shown as-is, never estimated.
//
// Uses jsPDF, loaded on demand from a CDN (esm.sh) — same
// load-only-when-needed pattern as heic2any (compressImage.js) and
// lamejs (compressAudio.js) elsewhere in this app, so nothing needed
// installing via package.json/node_modules for this to work.

import { roundOverallBand, formatBand } from './ieltsBands'

function withTimeout(promise, ms, label) {
  return Promise.race([
    promise,
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error(`${label} timed out — check your connection and try again.`)), ms)
    ),
  ])
}

let jsPDFModulePromise = null
function loadJsPDF() {
  if (!jsPDFModulePromise) {
    jsPDFModulePromise = withTimeout(
      import('https://esm.sh/jspdf@2.5.2'),
      20000,
      'Loading the PDF library'
    )
  }
  return jsPDFModulePromise
}

/*
 * skills: { listening, reading, writing, speaking } — each either null
 * (no result recorded yet) or { band, note } where `note` is a short
 * line shown under the band, e.g. "62% average — estimated" or
 * "Reviewed 12 Sep 2026".
 */
export async function downloadScoreReport({ studentName, targetBand, generatedFor, skills }) {
  const { jsPDF } = await loadJsPDF()
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })

  const pageWidth = doc.internal.pageSize.getWidth()
  const marginX = 48
  let y = 64

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.text('IELTS Mock Test — Score Report', marginX, y)

  y += 20
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(120)
  doc.text('Unofficial — generated by IELTS with Mr Ikromov. Not an IDP/British Council document.', marginX, y)
  doc.setTextColor(0)

  y += 32
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text(studentName || 'Student', marginX, y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(
    new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }),
    pageWidth - marginX,
    y,
    { align: 'right' }
  )

  if (generatedFor) {
    y += 16
    doc.setFontSize(10)
    doc.setTextColor(120)
    doc.text(generatedFor, marginX, y)
    doc.setTextColor(0)
  }

  if (targetBand != null) {
    y += 16
    doc.setFontSize(10)
    doc.text(`Target band: ${formatBand(targetBand)}`, marginX, y)
  }

  y += 28

  const rows = [
    ['Listening', skills?.listening],
    ['Reading', skills?.reading],
    ['Writing', skills?.writing],
    ['Speaking', skills?.speaking],
  ]

  const colSkillX = marginX
  const colBandX = marginX + 220
  const colNoteX = marginX + 300

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('Skill', colSkillX, y)
  doc.text('Band', colBandX, y)
  doc.text('Detail', colNoteX, y)
  y += 8
  doc.setDrawColor(190)
  doc.line(marginX, y, pageWidth - marginX, y)
  y += 22

  rows.forEach(([label, info]) => {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(0)
    doc.text(label, colSkillX, y)
    doc.setFont('helvetica', 'normal')
    doc.text(info ? formatBand(info.band) : '—', colBandX, y)
    doc.setFontSize(9)
    doc.setTextColor(120)
    doc.text(info?.note || 'No result recorded yet', colNoteX, y, { maxWidth: pageWidth - marginX - colNoteX })
    doc.setTextColor(0)
    y += 26
  })

  y += 6
  doc.setDrawColor(190)
  doc.line(marginX, y, pageWidth - marginX, y)
  y += 32

  const availableBands = rows.map(([, info]) => info?.band).filter((b) => b != null)
  const overall =
    availableBands.length > 0
      ? roundOverallBand(availableBands.reduce((sum, b) => sum + Number(b), 0) / availableBands.length)
      : null

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text('Overall band', marginX, y)
  doc.text(formatBand(overall), pageWidth - marginX, y, { align: 'right' })

  if (availableBands.length < 4) {
    y += 18
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(150)
    doc.text(
      `Based on ${availableBands.length} of 4 skills — the rest have no recorded result yet.`,
      marginX,
      y
    )
    doc.setTextColor(0)
  }

  y += 36
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(140)
  const disclaimer =
    'Listening and Reading bands are estimated from the raw percentage score using a commonly published approximate conversion table — they are not an official IELTS/IDP grading and can differ from a real test result. Writing and Speaking bands are given by a human examiner and are not estimated.'
  const disclaimerLines = doc.splitTextToSize(disclaimer, pageWidth - marginX * 2)
  doc.text(disclaimerLines, marginX, y)

  const safeName = (studentName || 'student').replace(/[^a-z0-9]+/gi, '-').toLowerCase()
  doc.save(`${safeName}-ielts-mock-score-report.pdf`)
}
